# Generated by Django 3.2.9 on 2021-11-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('name', models.CharField(help_text='hospital name', max_length=200)),
                ('city', models.CharField(help_text='hospital city', max_length=200)),
                ('pincode', models.CharField(help_text='pincode of city', max_length=10)),
                ('hospital_id', models.IntegerField(help_text='unique hospital id', primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(help_text='first name of patient', max_length=20)),
                ('last_name', models.CharField(help_text='last name of patient', max_length=20)),
                ('city', models.CharField(help_text='patient city', max_length=100)),
                ('pincode', models.CharField(help_text='pincode of patient city', max_length=10)),
                ('patient_id', models.IntegerField(help_text='unique id of patient', primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='available amount')),
                ('cost', models.IntegerField(help_text='cost per dose')),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coviapp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='available amount')),
                ('cost', models.IntegerField(help_text='cost per liter')),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coviapp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='no of available beds')),
                ('cost', models.IntegerField(help_text='cost per bed')),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coviapp.hospital')),
            ],
        ),
    ]
